# Default values for flask-aws-monitor
replicaCount: 2

image:
  repository: avigdol/flask-aws-monitor
  tag: "latest"
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 5001
  targetPort: 5001

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: flask-monitor.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

# AWS Environment Variables
# These should be set via Kubernetes secrets in production
env:
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_DEFAULT_REGION: "us-east-1"

# Node selector and tolerations
nodeSelector: {}
tolerations: []
affinity: {}

# Pod security context
podSecurityContext: {}

# Container security context
securityContext: {}

# Liveness and readiness probes
livenessProbe:
  httpGet:
    path: /
    port: 5001
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /
    port: 5001
  initialDelaySeconds: 5
  periodSeconds: 5