apiVersion: v1
kind: Service
metadata:
  name: flask-aws-monitor-service
  labels:
    app: flask-aws-monitor
    owner: RotemAv
spec:
  type: LoadBalancer
  ports:
  - port: 5001
    targetPort: 5001
    protocol: TCP
    name: http
  selector:
    app: flask-aws-monitor